<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMkuAYeu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMkuAYeu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMkuAYeu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMkuAYeu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMkuAYeu\App_KernelDevDebugContainer([
    'container.build_hash' => 'MkuAYeu',
    'container.build_id' => 'afb98dee',
    'container.build_time' => 1577967987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMkuAYeu');
